export enum UserRole {
  USER = 'USER',
  ADMIN = 'ADMIN',
  PROPERTY_OWNER = 'PROPERTY_OWNER',
  MANAGER = 'MANAGER',
}

export enum PropertyType {
  APARTMENT = 'APARTMENT',
  HOUSE = 'HOUSE',
  ROOM = 'ROOM',
  COMMERCIAL = 'COMMERCIAL',
  STORAGE = 'STORAGE',
  PLOT = 'PLOT',
  GARAGE = 'GARAGE',
  LUXURY = 'LUXURY',
  INVESTMENT = 'INVESTMENT',
}

export enum PropertyStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  MAINTENANCE = 'MAINTENANCE',
  SUSPENDED = 'SUSPENDED',
}

export enum CancellationPolicy {
  FLEXIBLE = 'FLEXIBLE',
  MODERATE = 'MODERATE',
  STRICT = 'STRICT',
  SUPER_STRICT = 'SUPER_STRICT',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CHECKED_IN = 'CHECKED_IN',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}

export enum PaymentMethod {
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  APPLE_PAY = 'APPLE_PAY',
  GOOGLE_PAY = 'GOOGLE_PAY',
  PAYPAL = 'PAYPAL',
  BANK_TRANSFER = 'BANK_TRANSFER',
  STRIPE_LINK = 'STRIPE_LINK',
}

export enum MaintenancePriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum MaintenanceStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum MessageType {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  FILE = 'FILE',
  SYSTEM = 'SYSTEM',
}

export enum NotificationType {
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  MAINTENANCE_REQUEST = 'MAINTENANCE_REQUEST',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  SYSTEM_UPDATE = 'SYSTEM_UPDATE',
}

export enum ContentStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum RoomType {
  BEDROOM = 'BEDROOM',
  LIVING_ROOM = 'LIVING_ROOM',
  STUDIO = 'STUDIO',
  KITCHEN = 'KITCHEN',
  BATHROOM = 'BATHROOM',
  BALCONY = 'BALCONY',
  TERRACE = 'TERRACE',
  GARDEN = 'GARDEN',
  OTHER = 'OTHER',
}

export enum CleaningFrequency {
  AFTER_EACH_BOOKING = 'AFTER_EACH_BOOKING',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  BIWEEKLY = 'BIWEEKLY',
  MONTHLY = 'MONTHLY',
  CUSTOM = 'CUSTOM',
}

export enum AnalyticsPeriod {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  YEARLY = 'YEARLY',
}

export enum NoteType {
  OWNER_NOTE = 'OWNER_NOTE',
  MAINTENANCE_NOTE = 'MAINTENANCE_NOTE',
  GUEST_PREFERENCE = 'GUEST_PREFERENCE',
  BUSINESS_NOTE = 'BUSINESS_NOTE',
  ADMIN_NOTE = 'ADMIN_NOTE',
}

// Content Management Enums
export enum ContentType {
  TEXT = 'TEXT',
  HTML = 'HTML',
  MARKDOWN = 'MARKDOWN',
  JSON = 'JSON',
  IMAGE = 'IMAGE',
  GALLERY = 'GALLERY',
  HERO = 'HERO',
}

export enum MediaCategory {
  ROOMS = 'ROOMS',
  COMMON_AREAS = 'COMMON_AREAS',
  AMENITIES = 'AMENITIES',
  GALLERY = 'GALLERY',
  HERO = 'HERO',
  LOGO = 'LOGO',
  GENERAL = 'GENERAL',
}

export enum SettingType {
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  BOOLEAN = 'BOOLEAN',
  JSON = 'JSON',
}

